version: '2'
services:

  mysql:
    container_name: mysql
    build: docker/mysql
    ports:
     - "3306:3306"
  
  postgres:
    container_name: postgres
    build: docker/postgres
    ports:
     - "5432:5432"
    environment:
     POSTGRES_USER: quartznet
     POSTGRES_PASSWORD: quartznet
     POSTGRES_DB: quartznet

  firebird:
    container_name: firebird
    build: docker/firebird
    ports:
     - "3050:3050"

  oracle:
    container_name: oracle
    build: docker/oracle
    ports:
     - "1521:1521"
    environment:
     - ORACLE_ALLOW_REMOTE:true
